### ISSUE TITLE
XAML Icon becode wrong color and blurred

### ISSUE THREAD

**Issue by pvolyntsev** [Eclo/Svg-To-Xaml-converter#1]
For the test I used icon "[test-tube.svg](https://www.dropbox.com/s/hmxtgwllo2qq8yp/test-tube.svg?dl=0)"
Your utility produced "[test-tube.xaml](https://www.dropbox.com/s/ohm92vordiq45ja/test-tube.xaml?dl=0)"
1. XAML icon is filled with white and displayed over the white background. It seems to be invisible.
   http://take.ms/zkoky
2. The original SVG is orange. The XAML icon is white.

I changed Fill="#000000" and icon become black http://take.ms/HIoxw 
1. Icon in XAML is blurred. I removed Stretch="Uniform" and it become pixel perfect.
   http://take.ms/bTVOn

P.S. I use [Kaxaml](http://kaxaml.com) utility to preview and edit XAML files.

**Comment by josesimoes** [comment]
fixed in commit 610213adaaedbe1eb2dafeb57c89121ba0268a1c
